version: '3.9'

services:
  backend:
    build:
      context: ./src/node-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
    networks:
      - langflow-network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_PORT=5173
      - VITE_PROXY_TARGET=http://backend:8000
    depends_on:
      - backend
    networks:
      - langflow-network

networks:
  langflow-network:
    driver: bridge
