version: '3.9'

services:
  backend:
    build:
      context: ./src/node-backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    network_mode: host
    environment:
      - NODE_ENV=development
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/health_check"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    network_mode: host
    environment:
      - NODE_ENV=development
      - PORT=5173
      - VITE_PROXY_TARGET=http://localhost:8000
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
